image: atlassian/default-image:2

# Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings

pipelines:
  default:
    - step:
        services:
          - docker
        script:
          - export IMAGE_NAME=kkodc/geo-builder:latest
          - docker build -t $IMAGE_NAME ./base
          # authenticate with the Docker Hub registry
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          # push the new Docker image to the Docker registry
          - docker push $IMAGE_NAME
definitions:
  services:
    docker:
      memory: 2048
