name: docker-latest
on: [workflow_dispatch]

env:
  BUILDER_IMAGE: opendatacube/geobase-builder:latest
  RUNNER_IMAGE: opendatacube/geobase-runner:latest

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Base Image (builder)
      run: |
        docker build --tag ${BUILDER_IMAGE} ./base/builder

    - name: Base Image (runner)
      run: |
        docker build \
          --build-arg base=${BUILDER_IMAGE} \
          --tag ${RUNNER_IMAGE} ./base/runner

    - name: DockerHub Push
      run: |
        echo "Login to DockerHub"
        echo "${{ secrets.DOCKERPASSWORD }}" | docker login -u "${{ secrets.DOCKERUSER }}" --password-stdin
        docker push ${BUILDER_IMAGE}
        docker push ${RUNNER_IMAGE}

    - name: Run vulnerability scanner (builder)
      uses: aquasecurity/trivy-action@0.0.6
      continue-on-error: true
      with:
        image-ref: "${{ env.BUILDER_IMAGE }}"
        format: "table"
        exit-code: "1"
        severity: "CRITICAL,HIGH"

    - name: Run vulnerability scanner (runner)
      uses: aquasecurity/trivy-action@0.0.6
      with:
        image-ref: "${{ env.RUNNER_IMAGE }}"
        format: "table"
        exit-code: "1"
        severity: "CRITICAL,HIGH"
