name: Docker Image CI

on:
  push:
    paths:
      - 'base/**'
      - 'local/**'
      - '.github/workflows/**'


env:
  ORG: opendatacube
  IMAGE: geobase
  DOCKER_USER: gadockersvc


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Base Image (builder)
      run: |
        docker pull ${ORG}/${IMAGE}:${tt} || true
        docker build \
              --cache-from ${ORG}/${IMAGE}:${tt} \
              --tag        ${ORG}/${IMAGE}:${tt} \
              ./base/${tt}
      env:
        tt: builder

    - name: Base Image (wheels)
      run: |
        docker pull ${ORG}/${IMAGE}:${tt} || true
        docker build \
              --cache-from ${ORG}/${IMAGE}:${tt} \
              --tag        ${ORG}/${IMAGE}:${tt} \
              ./base/${tt}
      env:
        tt: wheels

    - name: Base Image (runner)
      run: |
        docker pull ${ORG}/${IMAGE}:${tt} || true
        docker build \
              --cache-from ${ORG}/${IMAGE}:${tt} \
              --tag        ${ORG}/${IMAGE}:${tt} \
              ./base/${tt}
      env:
        tt: runner

    - name: Test Image (local)
      run: |
        docker build \
          --build-arg USER_NAME=$USER \
          --build-arg UID=$UID \
          --tag geobase:local ./local
        docker run --rm geobase:local gdal-config --version
        docker run --rm geobase:local gdal-config --formats

    - name: DockerHub Push
      if: github.ref == 'refs/heads/master'
      run: |
        echo "Login to DockerHub as ${DOCKER_USER}"
        echo "${{ secrets.DockerPassword }}" | docker login -u "${DOCKER_USER}" --password-stdin 
        docker push ${ORG}/${IMAGE}:builder
        docker push ${ORG}/${IMAGE}:runner
        docker push ${ORG}/${IMAGE}:wheels
