name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        if docker pull kkodc/geobase:builder ; then
           docker tag kkodc/geobase:builder local:cache
           echo "Using cache"
        else
           echo "Building from scratch"
        fi
        docker build --tag kkodc/geobase:builder --cache-from local:cache ./base
