name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Pull Base Image (builder)
      run: |
        if docker pull kkodc/geobase:builder ; then
           docker tag kkodc/geobase:builder local:builder
           echo "Using cache"
        else
           echo "Will build from scratch"
        fi

    - name: Build the Docker image (builder)
      run: |
        docker images
        docker build --tag kkodc/geobase:builder --cache-from local:builder ./base/builder

    - name: Pull Base Image (wheels)
      run: |
        if docker pull kkodc/geobase:wheels ; then
           docker tag kkodc/geobase:wheels local:wheels
           echo "Using cache"
        else
           echo "Will build from scratch"
        fi

    - name: Build the Docker image (wheels)
      run: |
        docker build --tag kkodc/geobase:wheels --cache-from local:wheels ./base/wheels

    - name: Pull Base Image (runner)
      run: |
        if docker pull kkodc/geobase:runner ; then
           docker tag kkodc/geobase:runner local:runner
           echo "Using cache"
        else
           echo "Will build from scratch"
        fi

    - name: Build the Docker image (runner)
      run: |
        docker build --tag kkodc/geobase:runner --cache-from local:runner ./base/runner

    - name: Build the Docker image (local)
      run: |
        docker build \
          --build-arg USER_NAME=$USER \
          --build-arg UID=$UID \
          --tag geobase:local ./local
        docker run --rm geobase:local gdal-config --version
        docker run --rm geobase:local gdal-config --formats

    - name: DockerHub Login
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/sample'
      env:
        docker_user: kkodc
        docker_password: ${{ secrets.DockerPassword }}
      run: docker login -u "${docker_user}" -p "${docker_password}"

    - name: DockerHub Push
      if: github.ref == 'refs/heads/master'
      run: |
        docker push kkodc/geobase:builder
        docker push kkodc/geobase:runner
        docker push kkodc/geobase:wheels

    - name: Build and publish sample (only on sample branch)
      if: github.ref == 'refs/heads/sample'
      run: |
        if docker pull kkodc/geobase:sample ; then
           docker tag kkodc/gebase:sample local:sample
           echo "Using cache"
        else
           echo "Will build from scratch"
        fi

        docker build --cache-from local:sample --tag kkodc/geobase:sample sample
        docker push kkodc/geobase:sample
