name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Pull Base Image (builder)
      run: |
        if docker pull kkodc/geobase:builder ; then
           docker tag kkodc/geobase:builder local:builder
           echo "Using cache"
        else
           echo "Will build from scratch"
        fi

    - name: Build the Docker image (builder)
      run: |
        docker images
        docker build --tag kkodc/geobase:builder --cache-from local:builder ./base

    - name: Pull Base Image (runner)
      run: |
        if docker pull kkodc/geobase:runner ; then
           docker tag kkodc/geobase:runner local:runner
           echo "Using cache"
        else
           echo "Will build from scratch"
        fi

    - name: Build the Docker image (runner)
      run: |
        docker build --tag kkodc/geobase:runner --cache-from local:runner ./runner

    - name: Build the Docker image (local)
      run: |
        docker build \
          --build-arg USER_NAME=$USER \
          --build-arg UID=$UID \
          --tag geobase:local ./local
        docker run --rm geobase:local gdal-config --version
        docker run --rm geobase:local gdal-config --formats


    - name: DockerHub Login
      env:
        docker_user: kkodc
        docker_password: ${{ secrets.DockerPassword }}
      run: docker login -u "${docker_user}" -p "${docker_password}"

    - name: DockerHub Push
      run: |
        docker push kkodc/geobase:builder
        docker push kkodc/geobase:runner
