name: docker-latest
on: [workflow_dispatch]

env:
  ORG: opendatacube
  IMAGE: geobase
  BUILDER_IMAGE_NAME: opendatacube/geobase:builder
  WHEELS_IMAGE_NAME: opendatacube/geobase:wheels
  RUNNER_IMAGE_NAME: opendatacube/geobase:runner

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Base Image (builder)
      run: |
        docker build --tag ${ORG}/${IMAGE}:builder ./base/builder

    - name: Base Image (wheels)
      run: |
        docker build \
          --build-arg base=${ORG}/${IMAGE}:builder \
          --tag ${ORG}/${IMAGE}:wheels ./base/wheels

    - name: Base Image (runner)
      run: |
        docker build \
          --build-arg base=${ORG}/${IMAGE}:builder \
          --tag ${ORG}/${IMAGE}:runner ./base/runner

    - name: DockerHub Push
      run: |
        echo "Login to DockerHub"
        echo "${{ secrets.DOCKERPASSWORD }}" | docker login -u "${{ secrets.DOCKERUSER }}" --password-stdin
        docker push ${ORG}/${IMAGE}:builder
        docker push ${ORG}/${IMAGE}:runner
        docker push ${ORG}/${IMAGE}:wheels

    - name: Run vulnerability scanner (builder)
      uses: aquasecurity/trivy-action@0.0.6
      continue-on-error: true
      with:
        image-ref: "${{ env.BUILDER_IMAGE_NAME }}"
        format: "table"
        exit-code: "1"
        severity: "CRITICAL,HIGH"

    - name: Run vulnerability scanner (wheels)
      uses: aquasecurity/trivy-action@0.0.6
      continue-on-error: true
      with:
        image-ref: "${{ env.WHEELS_IMAGE_NAME }}"
        format: "table"
        exit-code: "1"
        severity: "CRITICAL,HIGH"

    - name: Run vulnerability scanner (runner)
      uses: aquasecurity/trivy-action@0.0.6
      with:
        image-ref: "${{ env.RUNNER_IMAGE_NAME }}"
        format: "table"
        exit-code: "1"
        severity: "CRITICAL,HIGH"