name: Docker Image CI

on: [push]

env:
  ORG: opendatacube
  IMAGE: geobase
  DOCKER_USER: gadockersvc


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Base Image (builder)
      run: |
        docker pull ${ORG}/${IMAGE}:${tt} || true
        docker build \
              --cache-from ${ORG}/${IMAGE}:${tt} \
              --tag        ${ORG}/${IMAGE}:${tt} \
              ./base/${tt}
      env:
        tt: builder

    - name: Base Image (wheels)
      run: |
        docker pull ${ORG}/${IMAGE}:${tt} || true
        docker build \
              --cache-from ${ORG}/${IMAGE}:${tt} \
              --tag        ${ORG}/${IMAGE}:${tt} \
              ./base/${tt}
      env:
        tt: wheels

    - name: Base Image (runner)
      run: |
        docker pull ${ORG}/${IMAGE}:${tt} || true
        docker build \
              --cache-from ${ORG}/${IMAGE}:${tt} \
              --tag        ${ORG}/${IMAGE}:${tt} \
              ./base/${tt}
      env:
        tt: runner

    - name: Test Image (local)
      run: |
        docker build \
          --build-arg USER_NAME=$USER \
          --build-arg UID=$UID \
          --tag geobase:local ./local
        docker run --rm geobase:local gdal-config --version
        docker run --rm geobase:local gdal-config --formats

    - name: DockerHub Push
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/sandbox'
      run: |
        docker login -u "${DOCKER_USER}" -p "${{ secrets.DockerPassword }}"
        docker push ${ORG}/${IMAGE}:builder
        docker push ${ORG}/${IMAGE}:runner
        docker push ${ORG}/${IMAGE}:wheels

    # TODO: delete this
    - name: Build and publish sandbox (only on sandbox branch)
      if: github.ref == 'refs/heads/sandbox'
      run: |
        docker pull $build_base || true
        docker pull $base       || true

        docker build --target builder --cache-from $build_base --tag $build_base sandbox
        docker build --cache-from $base --cache-from $build_base --tag $base sandbox
        docker push $build_base
        docker push $base
      env:
        build_base: 'kkodc/sandbox:builder'
        base: 'kkodc/sandbox:latest'
