name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        if docker pull kkodc/geobase:builder ; then
           echo "Using cache"
           cache="--cache-from kkodc/geobase:builder"
        else
           echo "Building from scratch"
           cache=""
        fi
        docker build base --tag kkodc/geobase:builder $cache
